name: pynhd-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # pygeoogc deps
  - cytoolz
  - defusedxml
  - owslib
  - pyyaml
  - pyproj
  - requests
  - requests-cache
  - setuptools
  - shapely
  - simplejson
  - urllib3

  # pygeoutils deps
  - affine
  - geopandas
  - numpy
  - netcdf4
  - orjson
  - rasterio
  - xarray

  # pynhd deps
  - networkx
  - pandas
  - pyarrow

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck

  # test deps
  - pytest
  - pytest-cov
  - pytest-xdist
  - flaky

  - pip
  - pip:
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
