name: dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  # pygeoogc deps
  - aiodns
  - aiohttp
  - brotlipy
  - chardet
  - cytoolz
  - defusedxml
  - nest-asyncio
  - orjson
  - owslib
  - pyproj
  - requests
  - setuptools
  - shapely
  - simplejson

  # pygeoutils deps
  - geopandas
  - netCDF4
  - rasterio
  - xarray

  # pynhd deps
  - networkx
  - pyarrow

  # pygeohydro deps
  - folium
  - lxml
  - matplotlib-base
  - openpyxl

  # pydaymet deps
  # - lxml
  - dask-core
  - scipy

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck
  - descartes

  # test deps
  - pytest
  - pytest-xdist
  - pytest-sugar
  - flaky

  # dev deps
  - pre-commit
  - setuptools_scm
  - grayskull
  - profilehooks
  - tqdm
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - nb_black

  - pip
  - pip:
    - jupyterlab-spellchecker
    - nbmake

    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/pynhd.git
    - git+https://github.com/cheginit/pygeohydro.git
    - git+https://github.com/cheginit/py3dep.git
    - git+https://github.com/cheginit/pydaymet.git
